name: squid-app
region: sgp
domains:
  - domain: aloeducation.co.uk
    type: PRIMARY
  - domain: www.aloeducation.co.uk
    type: ALIAS
static_sites:
  - name: web-crm
    github:
      repo: engralaminn-collab/alo-education
      branch: main
      deploy_on_push: true
    build_command: corepack enable && pnpm install && pnpm run build
    output_dir: apps/web/dist
    catchall_document: index.html
    envs:
      - key: VITE_DISABLE_BASE44
        value: "true"
      - key: VITE_API_BASE_URL
        value: https://api.aloeducation.co.uk
    routes:
      - path: /
