name: squid-app
region: sgp
static_sites:
  - name: web-crm
    github:
      repo: https://github.com/engralaminn-collab/alo-education
      branch: main
      deploy_on_push: true
    build_command: npm ci && npm run build && test -d dist
    output_dir: dist
    envs:
      - key: VITE_DISABLE_BASE44
        value: "true"
      - key: VITE_API_BASE_URL
        value: https://api.aloeducation.co.uk
      - key: VITE_AUTH_LOGIN_URL
        value: https://aloeducation.co.uk/login
    routes:
      - path: /
    domains:
      - domain: www.aloeducation.co.uk
        type: PRIMARY
      - domain: crm.aloeducation.co.uk
        type: ALIAS
