import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    
    const { application_id } = await req.json();

    // Fetch application with related data
    const application = await base44.asServiceRole.entities.Application.get(application_id);
    const student = await base44.asServiceRole.entities.StudentProfile.get(application.student_id);
    const course = await base44.asServiceRole.entities.Course.get(application.course_id);
    const documents = await base44.asServiceRole.entities.Document.filter({ 
      student_id: application.student_id,
      application_id: application_id 
    });

    // AI Analysis Prompt
    const analysisPrompt = `
You are an expert education counselor AI. Analyze this student's application progress and identify bottlenecks, missing documents, and required actions.

Application Details:
- Status: ${application.status}
- Student: ${student.first_name} ${student.last_name}
- Course: ${course.course_title} at ${course.country}
- Intake: ${application.intake || 'Not specified'}
- Applied Date: ${application.applied_date || 'Not yet applied'}
- Offer Deadline: ${application.offer_deadline || 'N/A'}

Milestones Completed:
${JSON.stringify(application.milestones, null, 2)}

Documents Submitted:
${documents.map(d => `- ${d.document_type}: ${d.status}`).join('\n')}

Student Profile Completeness: ${student.profile_completeness || 0}%

Analyze and provide:
1. Critical bottlenecks (max 3)
2. Missing/required documents (max 5)
3. Recommended tasks for counselor with priority and deadline
4. Overall application health score (0-100)
5. Next best actions

Return structured JSON.
    `;

    const aiAnalysis = await base44.integrations.Core.InvokeLLM({
      prompt: analysisPrompt,
      response_json_schema: {
        type: "object",
        properties: {
          health_score: { type: "number" },
          bottlenecks: {
            type: "array",
            items: {
              type: "object",
              properties: {
                issue: { type: "string" },
                severity: { type: "string", enum: ["high", "medium", "low"] }
              }
            }
          },
          missing_documents: {
            type: "array",
            items: { type: "string" }
          },
          recommended_tasks: {
            type: "array",
            items: {
              type: "object",
              properties: {
                title: { type: "string" },
                description: { type: "string" },
                priority: { type: "string", enum: ["urgent", "high", "medium", "low"] },
                due_days: { type: "number" }
              }
            }
          },
          next_actions: {
            type: "array",
            items: { type: "string" }
          }
        }
      }
    });

    // Auto-create tasks for counselor
    const createdTasks = [];
    for (const task of aiAnalysis.recommended_tasks) {
      const dueDate = new Date();
      dueDate.setDate(dueDate.getDate() + task.due_days);

      const newTask = await base44.asServiceRole.entities.Task.create({
        title: task.title,
        description: task.description,
        type: 'document_review',
        student_id: application.student_id,
        application_id: application_id,
        assigned_to: student.counselor_id,
        status: 'pending',
        priority: task.priority,
        due_date: dueDate.toISOString().split('T')[0],
        notes: 'Auto-generated by AI analysis'
      });
      createdTasks.push(newTask);
    }

    return Response.json({
      success: true,
      analysis: aiAnalysis,
      tasks_created: createdTasks.length
    });

  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});